#!/usr/bin/env python3
"""Regenerate parquet fixtures. Needs sitting_duck and markdown installed. Run from repo root."""
import os, subprocess, duckdb
con = duckdb.connect()
con.execute("LOAD sitting_duck"); con.execute("LOAD markdown")
con.execute("""COPY (SELECT * REPLACE ('app.py' AS file_path) FROM read_ast('docs/examples/app.py'))
               TO 'test/data/app.parquet' (FORMAT PARQUET)""")
sd = os.path.expanduser("~/Projects/sitting_duck")
commit = subprocess.check_output(["git", "-C", sd, "rev-parse", "origin/main"]).decode().strip()
con.execute(f"""COPY (SELECT * REPLACE (replace(file_path, '{sd}/', '') AS file_path)
               FROM read_ast('{sd}/scripts/*.py')) TO 'test/data/scripts.parquet' (FORMAT PARQUET)""")
con.execute("COPY (FROM read_markdown_blocks('README.md')) TO 'test/data/readme_blocks.parquet' (FORMAT PARQUET)")
n_app = con.execute("SELECT count(*) FROM 'test/data/app.parquet'").fetchone()[0]
n_scr, n_files = con.execute("SELECT count(*), count(DISTINCT file_path) FROM 'test/data/scripts.parquet'").fetchone()
n_md = con.execute("SELECT count(*) FROM 'test/data/readme_blocks.parquet'").fetchone()[0]
open("test/data/FIXTURES.md", "w").write(f"""# Fixture provenance

Generated by `python3 test/gen_fixtures.py` with DuckDB {duckdb.__version__}.

| file | source | rows |
|---|---|---|
| app.parquet | sitting_duck `read_ast('docs/examples/app.py')` | {n_app} |
| scripts.parquet | sitting_duck `read_ast` over `sitting_duck/scripts/*.py` at commit `{commit}` | {n_scr} rows, {n_files} files |
| readme_blocks.parquet | markdown `read_markdown_blocks('README.md')` | {n_md} |
| employees.csv, categories.csv, coa.csv, ledger.csv | hand-written | see files |

Regenerating changes row counts if the sources changed; update the tests deliberately, never silently.
""")
print("ok", n_app, n_scr, n_files, n_md)
